import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const srcDir = path.join(__dirname, '../src');

function findRestaurantFiles(dir, relativePath = '', results = []) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  
  for (const entry of entries) {
    if (entry.name.startsWith('.') || entry.name === 'node_modules' || entry.name === 'pictures') {
      continue;
    }
    
    const fullPath = path.join(dir, entry.name);
    const newRelativePath = relativePath ? `${relativePath}/${entry.name}` : entry.name;
    
    if (entry.isDirectory()) {
      findRestaurantFiles(fullPath, newRelativePath, results);
    } else if (entry.isFile() && entry.name === 'Restaurants.jsx') {
      // Add listing page route
      const routePath = `/${newRelativePath.replace('/Restaurants.jsx', '/restaurants')}`;
      const importPath = `./${newRelativePath}`;
      results.push({
        path: routePath,
        importPath: importPath,
        type: 'listing'
      });
    }
  }
  
  return results;
}

const routes = findRestaurantFiles(srcDir);

// Generate the routes file
const routesContent = `// Auto-generated by scripts/generateListingRoutes.js
// This file maps URL paths to listing page components

export const listingRoutes = ${JSON.stringify(routes, null, 2)};

export function getListingComponent(path) {
  const route = listingRoutes.find(r => r.path === path);
  return route ? route.importPath : null;
}
`;

fs.writeFileSync(
  path.join(srcDir, 'listingRoutes.js'),
  routesContent
);

console.log(`✓ Generated ${routes.length} listing routes`);
routes.forEach(r => console.log(`  ${r.path}`));
